Aurora/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Social auth urls
    url('', include('social_django.urls', namespace='social')),
    # Aurora urls
    url(r'^$', 'cloud.views.pages.index', name='home'),
    url(r'^not_implemented/$', 'cloud.views.pages.not_implemented',
        name='not_implemented'),
    url(r'^cloud/', include('cloud.urls')),

    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # User login/logout
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'pages-login.html'}),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'pages-logout.html'}),
    url(r'^accounts/login-error/$', 'cloud.views.pages.login_error',
        name='login_error'),
)

cloud/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('cloud.views',
    #Virtual Machines
    url(r'^virtual_machines/$', 'virtual_machines.index',
        name='cloud-virtual-machines-index'),
    url(r'^virtual_machines/new/$', 'virtual_machines.new'),
    url(r'^virtual_machines/sync/$', 'virtual_machines.sync'),
    url(r'^virtual_machines/(?P<virtual_machine_id>\d+)/$',
        'virtual_machines.detail'),
    url(r'^virtual_machines/(?P<virtual_machine_id>\d+)/start/$',
        'virtual_machines.start'),
    url(r'^virtual_machines/(?P<virtual_machine_id>\d+)/stop/$',
        'virtual_machines.stop'),
    url(r'^virtual_machines/(?P<virtual_machine_id>\d+)/shutdown/$',
        'virtual_machines.shutdown'),
    url(r'^virtual_machines/(?P<virtual_machine_id>\d+)/resume/$',
        'virtual_machines.resume'),
    url(r'^virtual_machines/(?P<virtual_machine_id>\d+)/suspend/$',
        'virtual_machines.suspend'),
    url(r'^virtual_machines/(?P<virtual_machine_id>\d+)/delete/$',
        'virtual_machines.delete'),
    url(r'^virtual_machines/(?P<virtual_machine_id>\d+)/migrate/$',
        'virtual_machines.migrate'),
    url(r'^virtual_machines/(?P<virtual_machine_id>\d+)/xml/$',
        'virtual_machines.xml'),
    url(r'^virtual_machines/(?P<virtual_machine_id>\d+)/console/$',
        'virtual_machines.console'),
    url(r'^virtual_machines/(?P<virtual_machine_id>\d+)/interfaces/$',
        'virtual_machines.interfaces'),  # Webservice
    url(r'^virtual_machines/(?P<virtual_machine_id>\d+)/' +
        'new_virtual_interface/$', 'virtual_machines.new_virtual_interface'),

    #Devices (only webservices)
    url(r'^devices/(?P<device_type>\w+)/$', 'devices.devices'),  # Webservice
    url(r'^devices/(?P<device_id>\d+)/interfaces/$',
        'devices.interfaces'),  # Webservice

    #Hosts
    url(r'^hosts/$', 'hosts.index', name='cloud-hosts-index'),
    url(r'^hosts/new/$', 'hosts.new'),
    url(r'^hosts/(?P<host_id>\d+)/$', 'hosts.detail'),
    url(r'^hosts/(?P<host_id>\d+)/xml/$', 'hosts.xml'),
    url(r'^hosts/(?P<host_id>\d+)/delete/$', 'hosts.delete'),
    url(r'^hosts/(?P<host_id>\d+)/new_interface/$', 'hosts.new_interface'),
    url(r'^hosts/list_infrastructure/$', 'hosts.list_infrastructure'),
    url(r'^hosts/list_allocations/$', 'hosts.list_allocations'),
    url(r'^hosts/list_distances/$', 'hosts.list_distances'),

    #Switches
    url(r'^switches/$', 'switches.index', name='cloud-switches-index'),
    url(r'^switches/new/$', 'switches.new'),
    url(r'^switches/(?P<switch_id>\d+)/$', 'switches.detail'),
    url(r'^switches/(?P<switch_id>\d+)/delete/$', 'switches.delete'),
    url(r'^switches/(?P<switch_id>\d+)/new_port/$', 'switches.new_port'),
    url(r'^switches/(?P<switch_id>\d+)/connect_device/(?P<port_id>\d+)/$',
        'switches.connect_device'),

    #Images
    url(r'^images/$', 'images.index', name='cloud-images-index'),
    url(r'^images/new/$', 'images.new'),
    url(r'^images/(?P<image_id>\d+)/$', 'images.detail'),
    url(r'^images/(?P<image_id>\d+)/delete/$', 'images.delete'),

    #Templates
    url(r'^templates/$', 'templates.index', name='cloud-templates-index'),
    url(r'^templates/new/$', 'templates.new'),
    url(r'^templates/(?P<template_id>\d+)/$', 'templates.detail'),
    url(r'^templates/(?P<template_id>\d+)/delete/$', 'templates.delete'),

    #Virtual Links
    url(r'^virtual_links/$', 'virtual_links.index',
        name='cloud-virtual-links-index'),
    url(r'^virtual_links/new/$', 'virtual_links.new'),
    url(r'^virtual_links/sync/$', 'virtual_links.sync'),
    url(r'^virtual_links/(?P<virtual_link_id>\d+)/$', 'virtual_links.detail'),
    url(r'^virtual_links/(?P<virtual_link_id>\d+)/delete/$',
        'virtual_links.delete'),

    #Virtual Routers
    url(r'^virtual_routers/$', 'virtual_routers.index',
        name='cloud-virtual-routers-index'),
    url(r'^virtual_routers/new/$', 'virtual_routers.new'),
    url(r'^virtual_routers/(?P<virtual_router_id>\d+)/$',
        'virtual_routers.detail'),
    url(r'^virtual_routers/(?P<virtual_router_id>\d+)/delete/$',
        'virtual_routers.delete'),
    url(r'^virtual_routers/(?P<virtual_router_id>\d+)/new_remote_controller/$',
        'virtual_routers.new_remote_controller'),
    url(r'^virtual_routers/(?P<virtual_router_id>\d+)/new_virtual_interface/$',
        'virtual_routers.new_virtual_interface'),
    url(r'^virtual_routers/(?P<virtual_router_id>\d+)/delete_remote_controller/(?P<remote_controller_id>\d+)/$',
        'virtual_routers.delete_remote_controller'),
    url(r'^virtual_routers/(?P<virtual_router_id>\d+)/delete_virtual_interface/(?P<virtual_interface_id>\d+)/$',
        'virtual_routers.delete_virtual_interface'),
    url(r'^virtual_routers/(?P<virtual_router_id>\d+)/' +
        'connect_virtual_device/(?P<virtual_interface_id>\d+)/$',
        'virtual_routers.connect_virtual_device'),

    #Virtual Devices (only webservices)
    url(r'^virtual_devices/(?P<virtual_device_type>\w+)/$',
        'virtual_devices.virtual_devices'),  # Webservice
    url(r'^virtual_devices/(?P<virtual_device_id>\d+)/virtual_interfaces/$',
        'virtual_devices.virtual_interfaces'),  # Webservice

    #Slices
    url(r'^slices/$', 'slices.index', name='cloud-slices-index'),
    url(r'^slices/new/$', 'slices.new'),
    url(r'^slices/new_remote/$', 'slices.new_remote'),
    url(r'^slices/delete_remote/(?P<slice_name>[-\w]+)/$',
        'slices.delete_remote'),
    url(r'^slices/(?P<slice_id>\d+)/$', 'slices.detail'),
    url(r'^slices/(?P<slice_id>\d+)/deploy/$', 'slices.deploy'),
    url(r'^slices/(?P<slice_id>\d+)/delete/$', 'slices.delete'),
    url(r'^slices/(?P<slice_id>\d+)/add_optimization_program/$',
        'slices.add_optimization_program'),
    url(r'^slices/(?P<slice_id>\d+)/remove_optimization_program/' +
        '(?P<optimizes_id>\d+)/$', 'slices.remove_optimization_program'),
    url(r'^slices/export_all_flexcms/$', 'slices.export_all_flexcms'),

    #Gadgets
    url(r'^gadgets/resource_list/$', 'gadgets.resource_list'),
    url(r'^gadgets/virtual_resource_list/$', 'gadgets.virtual_resource_list'),
    url(r'^gadgets/aggregate_memory_usage/$', 'gadgets.aggregate_memory_usage'),
    url(r'^gadgets/aggregate_cpu_usage/$', 'gadgets.aggregate_cpu_usage'),

    #Programs
    url(r'^deployment_programs/$', 'deployment_programs.index',
        name='cloud-deployment-programs-index'),
    url(r'^deployment_programs/new/$', 'deployment_programs.new'),
    url(r'^deployment_programs/(?P<deployment_program_id>\d+)/$',
        'deployment_programs.detail'),
    url(r'^deployment_programs/(?P<deployment_program_id>\d+)/delete/$',
        'deployment_programs.delete'),
    url(r'^optimization_programs/$', 'optimization_programs.index',
        name='cloud-optimization-programs-index'),
    url(r'^optimization_programs/new/$', 'optimization_programs.new'),
    url(r'^optimization_programs/(?P<optimization_program_id>\d+)/$',
        'optimization_programs.detail'),
    url(r'^optimization_programs/(?P<optimization_program_id>\d+)/delete/$',
        'optimization_programs.delete'),
    url(r'^optimization_programs/ws/(?P<program_name>\w+)/$',
        'optimization_programs.web_services'),
    url(r'^metrics/$', 'metrics.index', name='cloud-metrics-index'),
    url(r'^metrics/new/$', 'metrics.new'),
    url(r'^metrics/(?P<metric_id>\d+)/$', 'metrics.detail'),
    url(r'^metrics/(?P<metric_id>\d+)/delete/$', 'metrics.delete'),
    url(r'^metrics/ws/(?P<metric_name>\w+)/$', 'metrics.web_services'),
    url(r'^events/$', 'events.index', name='cloud-events-index'),
    url(r'^events/new/$', 'events.new'),
    url(r'^events/(?P<event_id>\d+)/$', 'events.detail'),
    url(r'^events/(?P<event_id>\d+)/delete/$', 'events.delete'),

    #Monitoring
    url(r'^monitoring/settings/$', 'monitoring.settings',
        name='cloud-monitoring-settings'),

)

urls.py
from django.conf.urls.defaults import patterns, include, url

# Enabling Django contrib admin
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Social auth urls
    url(r'', include('social_auth.urls')),
    # Aurora urls
    url(r'^$', 'manager.views.pages.index', name='home'),
    url(r'^not_implemented/$', 'manager.views.pages.not_implemented',
        name='not_implemented'),
    url(r'^manager/', include('manager.urls')),

    # Django admin docs
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Django admin url
    url(r'^admin/', include(admin.site.urls)),

    # User login/logout
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'pages-login.html'}),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'pages-logout.html'}),
    url(r'^accounts/login-error/$', 'manager.views.pages.login_error',
        name='login_error'),

)

cloud/models/base_model.py
import logging
from django.db import models

class BaseModel(models.Model):
    class Meta:
        # Makes django recognize model in split modules
        app_label = 'cloud'
        # Turns this into an abstract model (does not create table for it)
        abstract = True

    # Default exception for models in cloud
    class ModelException(Exception):
        # Get an instance of a logger
        logger = logging.getLogger(__name__)

        def __init__(self, msg):
            self.msg = msg
            self.logger.warning(msg)

        def __str__(self):
            return repr(self.msg)

cloud/models/base_singleton_model.py
import logging
from django.db import models

class BaseSingletonModel(models.Model):
    """Singleton Model
 
    Ensures there's always only one entry in the database, and can fix the
    table (by deleting extra entries) even if added via another mechanism.
 
    Also has a static load() method which always returns the object - from
    the database if possible, or a new empty (default) instance if the
    database is still empty. If your instance has sane defaults (recommended),
    you can use it immediately without worrying if it was saved to the
    database or not.
 
    Useful for things like system-wide user-editable settings.
    """

    class Meta:
        # Makes django recognize model in split modules
        app_label = 'cloud'
        # Turns this into an abstract model (does not create table for it)
        abstract = True

    # Allows only one instance of submodels
    def save(self, *args, **kwargs):
        """
        Save object to the database. Removes all other entries if there
        are any.
        """
        self.__class__.objects.exclude(id=self.id).delete()
        super(BaseSingletonModel, self).save(*args, **kwargs)

    @classmethod
    def load(cls):
        """
        Load object from the database. Failing that, create a new empty
        (default) instance of the object and return it (without saving it
        to the database).
        """
        try:
            return cls.objects.get()
        except cls.DoesNotExist:
            return cls()

    # Default exception for models in cloud
    class SingletonModelException(Exception):
        # Get an instance of a logger
        logger = logging.getLogger(__name__)

        def __init__(self, msg):
            self.msg = msg
            self.logger.warning(msg)

        def __str__(self):
            return repr(self.msg)

cloud/models/deployment_program.py
import logging
from django.db import models
from cloud.models.program import Program

class DeploymentProgram(Program):

    class DeploymentProgramException(Program.ProgramException):
        # Alter logger to use this file name instead
        logger = logging.getLogger(__name__)

cloud/models/device.py
import logging
from django.db import models
from cloud.models.base_model import BaseModel

# Get an instance of a logger
logger = logging.getLogger(__name__)

class Device(BaseModel):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)

    def is_host(self):
        return hasattr(self, "host")

    def is_switch(self):
        return hasattr(self, "switch")

    def is_router(self):
        return hasattr(self, "router")

    def __unicode__(self):
        return self.name

    class DeviceException(BaseModel.ModelException):
        pass

cloud/models/event.py
import logging
from django.db import models
from cloud.models.base_model import BaseModel

EVENT_STATES = (
        (u'enabled', u'Enabled'),
        (u'disabled', u'Disabled'),
)
RELATIONAL_OPERATION = (
        (u'eq', u'(=) Equals'),
        (u'gt', u'(>) Greater Than'),
        (u'eqgt', u' (>=) Equals or Greater Than'),
        (u'lt', u'(<) Less Than'),
        (u'eqlt', u'(<=) Equals or Less Than'),
        (u'diff', u'(!=) Different'),
)


class Event(BaseModel):
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(blank=True, null=True)
    state = models.CharField(
        max_length=10,
        choices=EVENT_STATES,
        default='enabled', db_index=True
    )
    belongs_to_slice = models.ForeignKey(
        'Slice',  # Import as string to avoid circular import problems
        blank=True,
        null=True
    )
    metric = models.ForeignKey(
        'Metric',  # Import as string to avoid circular import problems
    )
    relational_operation = models.CharField(
        max_length=10,
        choices=RELATIONAL_OPERATION,
        default='eq', db_index=True
    )
    value = models.CharField(max_length=200, unique=True)
    program = models.ForeignKey(
        # Import as string to avoid circular import problems
        'OptimizationProgram',
    )

    def __unicode__(self):
        return self.name

    class EventException(BaseModel.ModelException):
        # Alter logger to use this file name instead
        logger = logging.getLogger(__name__)

cloud/models/metric.py
import logging
from django.db import models
from cloud.models.base_model import BaseModel

RETURN_DATA_TYPE = (
        (u'counter', u'Counter'),
        (u'number', u'Number'),
        (u'text', u'Text'),
        (u'object', u'Object'),
)
METRIC_STATES = (
        (u'enabled', u'Enabled'),
        (u'disabled', u'Disabled'),
)
METRIC_SCOPES = (
    (u'slice', u'Slice specific'),
    (u'infra', u'Infrastructure'),
)

class Metric(BaseModel):
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(blank=True, null=True)
    file = models.FileField(upload_to='metrics')
    returns = models.CharField(
        max_length=10,
        choices=RETURN_DATA_TYPE,
        default='number', db_index=True
    )
    state = models.CharField(
        max_length=10,
        choices=METRIC_STATES,
        default='enabled', db_index=True
    )
    scope = models.CharField(
        max_length=10,
        choices=METRIC_SCOPES,
        default='infra', db_index=True
    )

    def get_size(self):
        return self.file.file.size

    def __unicode__(self):
        return self.name

    class MetricException(BaseModel.ModelException):
        # Alter logger to use this file name instead
        logger = logging.getLogger(__name__)

cloud/models/optimization_program.py
import logging
from django.db import models
from cloud.models.program import Program

OPTMIZATION_SCOPES = (
    (u'slice', u'Slice specific'),
    (u'global', u'Global'),
)

class OptimizationProgram(Program):
    scope = models.CharField(max_length=10, choices=OPTMIZATION_SCOPES, default='global', db_index=True)

    class OptimizationProgramException(Program.ProgramException):
        # Alter logger to use this file name instead
        logger = logging.getLogger(__name__)

cloud/models/router.py
from django.db import models
from cloud.models.device import Device

ROUTER_TYPE = (
        (u'router', u'IP Router'),
)

class Router(Device):
    hostname = models.CharField(max_length=200)
    rt_type = models.CharField(max_length=10, choices=ROUTER_TYPE, default='router', db_index=True)

    def __unicode__(self):
        return self.hostname

    class RouterException(Device.DeviceException):
        pass

cloud/models/switch.py
from django.db import models
from cloud.models.device import Device
from cloud.helpers.ping import Ping

SWITCH_TYPE = (
        (u'ethernet', u'Ethernet Switch'),
        (u'openflow', u'Openflow Switch'),
)

class Switch(Device):
    hostname = models.CharField(max_length=200)
    sw_type = models.CharField(max_length=10, choices=SWITCH_TYPE, default='ethernet', db_index=True)

    def total_ports(self):
        return self.port_set.count()

    def current_state(self):
        return "Active" # TODO: Fix problem with Ping
        try:
            delay = Ping(self.hostname).run()
            return "Active (" + str(round(delay*1000, 2)) + " ms)"
        except Exception as e:
            return "Off-line (" + str(e) + ")"

    class SwitchException(Device.DeviceException):
        pass

cloud/templates/base-home-ajax.html
{% block content %}{% endblock %}

cloud/templates/gadgets-aggregate-memory-usage.html
{% load utils %}
{% if memory_stats %}
    <table class="table table-striped table-hover">
      <thead>
        <tr>
            <th>Type</th>
            <th>Total</th>
        </tr>
      </thead>
      <tbody>
        <tr>
        	<td>Total</td>
            <td class="number">{{ memory_stats.total|unit_convert:"KB" }}</td>
        </tr>
        <tr>
            <td>Cached</td>
            <td class="number">{{ memory_stats.cached|unit_convert:"KB" }}</td>
        </tr>
        <tr>
        	<td>Buffers</td>
            <td class="number">{{ memory_stats.buffers|unit_convert:"KB" }}</td>
        </tr>
        <tr>
        	<td>Free</td>
            <td class="number">{{ memory_stats.free|unit_convert:"KB" }}</td>
        </tr>
      </tbody>
    </table>
{% else %}
    <p><b>No statistics available.</b></p>
{% endif %}

cloud/templates/gadgets-resource-list.html
{% if resource_list %}
    <table class="table table-striped table-hover">
      <thead>
        <tr>
            <th>Resource Type</th>
            <th>Total</th>
        </tr>
      </thead>
      <tbody>
        {% for resource in resource_list %}
        <tr>
            <td>{{ resource.label }}</a></td>
            <td class="number">{{ resource.count }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% else %}
    <p><b>No resource list available.</b></p>
{% endif %}

cloud/templates/hosts-index.html
{% extends "base-content.html" %}
{% block content-body %}
  {% if host_list %}
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
          <th>Hostname</th>
          <th>Driver</th>
          <th>Transport</th>
          <th>State</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
      {% for host in host_list %}
        <tr>
          <td><a href="/Aurora/cloud/hosts/{{ host.id }}/">{{ host.hostname }}</a></td>
          <td>{{ host.get_driver_display }}</td>
          <td>{{ host.get_transport_display }}</td>
          <td>{{ host.current_state }}</td>
          <td>
          {% if host.current_state == "Active" %}
            <a class="btn btn-xs btn-default" href="/Aurora/cloud/hosts/{{ host.id }}/xml/">XML</a> 
          {% endif %}
           	<a class="btn btn-xs btn-danger" href="/Aurora/cloud/hosts/{{ host.id }}/delete/">Delete</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No Hosts are available.</p>
  {% endif %}
{% endblock %}

cloud/templates/metrics-detail.html
{% extends "base-content.html" %}
{% load utils %}
{% load pygmentize %}
{% block content-body %}
{% if metric %}
<div class="row">
  <div class="col-md-12">
    <h4>Metric Configuration</h4>
    <table class="table table-striped table-hover table-bordered">
      <tbody>
        <tr>
          <td><b>Name</b></td>
          <td>{{ metric.name }}</td>
        </tr>
        <tr>
          <td><b>Size</b></td>
          <td>{{ metric.get_size|unit_convert:"B" }}</td>
        </tr>
        <tr>
          <td><b>Data Type</b></td>
          <td>{{ metric.get_returns_display }}</td>
        </tr>
        <tr>
          <td><b>Scope</b></td>
          <td>{{ metric.get_scope_display }}</td>
        </tr>
        <tr>
          <td><b>State</b></td>
          <td>
            {% if metric.get_state_display == "Enabled" %}
              <span class="label label-success">
            {% else %}
              <span class="label label-default">
            {% endif %}
                {{ metric.get_state_display }}
              </span>
            </td>
        </tr>
        <tr>
          <td><b>Description</b></td>
          <td>{{ metric.description }}</td>
        </tr>
      </tbody>
    </table>

    <h4>File Contents</h4>
    {% if metric.file %}
      {{ ""|pygmentize_css }}
      <code class="python">{{ metric.file.read|pygmentize }}</code>
    {% endif %}
  </div>
</div>
{% endif %}
{% endblock %}

cloud/templates/metrics-index.html
{% extends "base-content.html" %}
{% load utils %}
{% block content-body %}
<div class="row">
  <div class="col-md-12">
  {% if metric_list %}
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
            <th>Name</th>
            <th>Size</th>
            <th>Data Type</th>
            <th>Scope</th>
            <th>State</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
      </thead>
      <tbody>
      {% for metric in metric_list %}
        <tr>
            <td><a href="/Aurora/cloud/metrics/{{ metric.id }}/">{{ metric }}</a></td>
            <td>{% if metric.file %}
                {{ metric.file.file.size|unit_convert:"B" }}
                {% endif %}
            </td>
            <td>{{ metric.get_returns_display }}</td>
            <td>{{ metric.get_scope_display }}</td>
            <td>{{ metric.get_state_display }}</td>
            <td>{{ metric.description }}</td>
            <td><a class="btn btn-xs btn-danger" href="/Aurora/cloud/metrics/{{ metric.id }}/delete/">Delete</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
{% else %}
    <p>No Metrics are available.</p>
{% endif %}
  </div>
</div>
{% endblock %}

cloud/templates/optimization-programs-detail.html
{% extends "base-content.html" %}
{% load utils %}
{% load pygmentize %}
{% block content-body %}
{% if program %}
<div class="row">
  <div class="col-md-12">
    <h4>Optimization Program Configuration</h4>
    <table class="table table-striped table-hover table-bordered">
      <tbody>
        <tr>
          <td><b>Name</b></td>
          <td>{{ program.name }}</td>
        </tr>
        <tr>
          <td><b>Size</b></td>
          <td>{{ program.get_size|unit_convert:"B" }}</td>
        </tr>
        <tr>
          <td><b>Scope</b></td>
          <td>{{ program.get_scope_display }}</td>
        </tr>
        <tr>
          <td><b>State</b></td>
          <td>
            {% if program.get_state_display == "Enabled" %}
              <span class="label label-success">
            {% else %}
              <span class="label label-default">
            {% endif %}
                {{ program.get_state_display }}
              </span>
            </td>
        </tr>
        <tr>
          <td><b>Description</b></td>
          <td>{{ program.description }}</td>
        </tr>
      </tbody>
    </table>

    <h4>File Contents</h4>
    {% if program.file %}
      {{ ""|pygmentize_css }}
      <code class="python">{{ program.file.read|pygmentize }}</code>
    {% endif %}
  </div>
</div>
{% endif %}
{% endblock %}

cloud/templates/optimization-programs-index.html
{% extends "base-content.html" %}
{% load utils %}
{% block content-body %}
<div class="row">
  <div class="col-md-12">
  {% if program_list %}
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
            <th>Name</th>
            <th>Size</th>
            <th>Scope</th>
            <th>State</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
      </thead>
      <tbody>
      {% for program in program_list %}
        <tr>
            <td><a href="/Aurora/cloud/optimization_programs/{{ program.id }}/">{{ program }}</a></td>
            <td>{% if program.file %}
                {{ program.file.file.size|unit_convert:"B" }}
                {% endif %}
            </td>
            <td>{{ program.get_scope_display }}</td>
            <td>{{ program.get_state_display }}</td>
            <td>{{ program.description }}</td>
            <td><a class="btn btn-xs btn-danger" href="/Aurora/cloud/optimization_programs/{{ program.id }}/delete/">Delete</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
{% else %}
    <p>No Programs are available.</p>
{% endif %}
  </div>
</div>
{% endblock %}

cloud/templates/switches-index.html
{% extends "base-content.html" %}
{% block content-body %}
  {% if switch_list %}
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Type</th>
          <th>Ports</th>
          <th>State</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
      {% for switch in switch_list %}
        <tr>
            <td><a href="/Aurora/cloud/switches/{{ switch.id }}/">{{ switch.name }}</a></td>
            <td>{{ switch.description }}</td>
            <td>{{ switch.get_sw_type_display }}</td>
            <td>{{ switch.total_ports }}</td>
            <td>{{ switch.current_state }}</td>
            <td><a class="btn btn-xs btn-danger" href="/Aurora/cloud/switches/{{ switch.id }}/delete/">Delete</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
{% else %}
    <p>No Switches are available.</p>
{% endif %}
{% endblock %}